{% set name = "vispy" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f4cf863a1c6142338d06cf3f824e75373dd45a4ce9a9a133e1c36b662f49aa1
  patches:
    - ctypes_fontconfig.diff

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - numpy
    - fontconfig  # [unix]
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fontconfig  # [unix]
    - freetype-py

test:
  imports:
    - vispy
  # todo: check headless testing
  #requires:
  #  - pyqt 5.*
  #commands:
  #  - python -c "import vispy; print(vispy.sys_info()); vispy.test()"

about:
  home: http://vispy.org/
  license_family: BSD
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'VisPy is a high-performance interactive 2D/3D data visualization library.'

extra:
  recipe-maintainers:
    - djhoese
    - kmuehlbauer
