{% set name = "vispy" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61527d5aa22ac54e2439208a6d062a5d81d685eb558a932753e6f2d6e4fd5a10
  patches:
    - ctypes_fontconfig.diff
    - 1789-filter-qnotifier-warning.patch

build:
  skip: true  # [py==27]
  number: 100
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - numpy
    - fontconfig  # [unix]
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fontconfig  # [unix]
    - freetype-py
    # needed for pkg_resources
    - setuptools

test:
  imports:
    - vispy
  # TODO: check headless testing
  # requires:
  #  - pyqt >=5.0
  # commands:
  #  - python -c "import vispy; print(vispy.sys_info()); vispy.test()"

about:
  home: http://vispy.org/
  license_family: BSD
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'VisPy is a high-performance interactive 2D/3D data visualization library.'

extra:
  recipe-maintainers:
    - djhoese
    - kmuehlbauer
    - hadim
