{% set version = "0.6.0" %}

package:
  name: vispy
  version: {{ version }}

source:
  fn: vispy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/v/vispy/vispy-{{ version }}.tar.gz
  sha256: e5a1199a84060b6c4b15d46cdf97dc679fe337a61ccc7db35e0644cc11ee753d
  patches:
    - ctypes_fontconfig.diff

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy
    - fontconfig  # [unix]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fontconfig  # [unix]

test:
  imports:
    - vispy
  # todo: check headless testing
  #requires:
  #  - pyqt 4.*
  #commands:
  #  - python -c "import vispy; print(vispy.sys_info()); vispy.test()"

about:
  home: http://vispy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'VisPy is a high-performance interactive 2D/3D data visualization library.'

extra:
  recipe-maintainers:
    - djhoese
    - kmuehlbauer
