appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: am1lyVMsP/OIu4Qn8IdinynHrUTnYtNKuR5zCJw/fyHh3F/EmVPuGHQmWWiee/zotcyReX/5BD4HHqexgwN2CnNlg0MI9flU1q4S9QWvkIcb6S6z4NqWeIXzAkRkt97jLz4hGXnTMrzh/4tP/l3wtq4hmmrgfnoWXZMe7vGDdTJREXwlP1lLbEYoB82JUJquz/s5YCnuU32Szkeq6wW22UzW49vwnkzlAo0enimXosgvQih9gf5J3jMf63Rg/2661beUOHIy13IQQLRLOw7zGgH6PgvqRMitIGZ6HRk+u+iIDUUXDBrrdUU6y+B6IZ9wzghLISQ34uyutPJFQsjDQ6t+trIRLL1qexqW2SShDGCkwL55hR2DjqAK41tv+MEx9BHbb3IDo8ycG5M6raC5s8suGJvpsayaAM30Fh72piKqirCQgC8uEIM9Ynpvj+7Hk1I1hU1DRwSyPHNEB2eOgUtj4RuFmlvf1SWLbK2Vhr0T761tKkLm4LoswgH3ZnlL6aMQeXEx8uxtfmWUpyoE7sX0zKW9eELkyV+TVX+jatvMBqnU5O/LtEbkfi9NMh8+Z0MYixBzG3r5KWfd7E0iao/9Vn5fykznzyNWnaZc9CbPHF6mJYqgeneuzje44zzzFmM7q5iwFTNVrQAv474y+kBY1yszQPbgZ+4RRlnR2h8=}
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
  win: azure
